databaseChangeLog:
  - logicalFilePath: product_category_table.yaml

  - changeSet:
      logicalFilePath: product_category_table.yaml
      id: 2
      author: anderson malheiro
      comment: creating product categories table
      changes:
        - sql:
            sql: >
              create table product_categories
              (
                  id serial
                      constraint product_categories_pk
                          primary key,
                  name varchar not null,
                  description varchar,
                  created_at timestamp with time zone default CURRENT_TIMESTAMP,
                  updated_at timestamp with time zone default CURRENT_TIMESTAMP
              );
